from datetime import datetime, timedelta

# Simple 5x7 font for uppercase letters, numbers, and symbols
FONT = {
    "A": [
        "  X  ",
        " X X ",
        "X   X",
        "XXXXX",
        "X   X",
    ],
    "B": [
        "XXXX ",
        "X   X",
        "XXXX ",
        "X   X",
        "XXXX ",
    ],
    "C": [
        " XXXX",
        "X    ",
        "X    ",
        "X    ",
        " XXXX",
    ],
    "D": [
        "XXXX ",
        "X   X",
        "X   X",
        "X   X",
        "XXXX ",
    ],
    "E": [
        "XXXXX",
        "X    ",
        "XXXX ",
        "X    ",
        "XXXXX",
    ],
    "F": [
        "XXXXX",
        "X    ",
        "XXXX ",
        "X    ",
        "X    ",
    ],
    "G": [
        " XXXX",
        "X    ",
        "X  XX",
        "X   X",
        " XXXX",
    ],
    "H": [
        "X   X",
        "X   X",
        "XXXXX",
        "X   X",
        "X   X",
    ],
    "I": [
        "XXXXX",
        "  X  ",
        "  X  ",
        "  X  ",
        "XXXXX",
    ],
    "J": [
        "XXXXX",
        "   X ",
        "   X ",
        "X  X ",
        " XX  ",
    ],
    "K": [
        "X   X",
        "X  X ",
        "XXX  ",
        "X  X ",
        "X   X",
    ],
    "L": [
        "X    ",
        "X    ",
        "X    ",
        "X    ",
        "XXXXX",
    ],
    "M": [
        "X   X",
        "XX XX",
        "X X X",
        "X   X",
        "X   X",
    ],
    "N": [
        "X   X",
        "XX  X",
        "X X X",
        "X  XX",
        "X   X",
    ],
    "O": [
        " XXX ",
        "X   X",
        "X   X",
        "X   X",
        " XXX ",
    ],
    "P": [
        "XXXX ",
        "X   X",
        "XXXX ",
        "X    ",
        "X    ",
    ],
    "Q": [
        " XXX ",
        "X   X",
        "X   X",
        "X  X ",
        " XX X",
    ],
    "R": [
        "XXXX ",
        "X   X",
        "XXXX ",
        "X  X ",
        "X   X",
    ],
    "S": [
        " XXXX",
        "X    ",
        " XXX ",
        "    X",
        "XXXX ",
    ],
    "T": [
        "XXXXX",
        "  X  ",
        "  X  ",
        "  X  ",
        "  X  ",
    ],
    "U": [
        "X   X",
        "X   X",
        "X   X",
        "X   X",
        " XXX ",
    ],
    "V": [
        "X   X",
        "X   X",
        "X   X",
        " X X ",
        "  X  ",
    ],
    "W": [
        "X   X",
        "X   X",
        "X X X",
        "XX XX",
        "X   X",
    ],
    "X": [
        "X   X",
        " X X ",
        "  X  ",
        " X X ",
        "X   X",
    ],
    "Y": [
        "X   X",
        " X X ",
        "  X  ",
        "  X  ",
        "  X  ",
    ],
    "Z": [
        "XXXXX",
        "   X ",
        "  X  ",
        " X   ",
        "XXXXX",
    ],
    "0": [
        " XXX ",
        "X   X",
        "X   X",
        "X   X",
        " XXX ",
    ],
    "1": [
        "  X  ",
        " XX  ",
        "  X  ",
        "  X  ",
        " XXX ",
    ],
    "2": [
        " XXX ",
        "X   X",
        "   X ",
        "  X  ",
        "XXXXX",
    ],
    "3": [
        " XXX ",
        "X   X",
        "  XX ",
        "X   X",
        " XXX ",
    ],
    "4": [
        "X  X ",
        "X  X ",
        "XXXXX",
        "   X ",
        "   X ",
    ],
    "5": [
        "XXXXX",
        "X    ",
        "XXXX ",
        "    X",
        "XXXX ",
    ],
    "6": [
        " XXX ",
        "X    ",
        "XXXX ",
        "X   X",
        " XXX ",
    ],
    "7": [
        "XXXXX",
        "   X ",
        "  X  ",
        " X   ",
        "X    ",
    ],
    "8": [
        " XXX ",
        "X   X",
        " XXX ",
        "X   X",
        " XXX ",
    ],
    "9": [
        " XXX ",
        "X   X",
        " XXXX",
        "    X",
        " XXX ",
    ],
    "!": [
        "  X  ",
        "  X  ",
        "  X  ",
        "     ",
        "  X  ",
    ],
    "@": [
        " XXX ",
        "X   X",
        "X XXX",
        "X    ",
        " XXX ",
    ],
    "#": [
        " X X ",
        "XXXXX",
        " X X ",
        "XXXXX",
        " X X ",
    ],
    "$": [
        "  X  ",
        " XXXX",
        "X X  ",
        " XXXX",
        "  X  ",
    ],
    "%": [
        "X  X ",
        "   X ",
        "  X  ",
        " X   ",
        "X  X ",
    ],
    "^": [
        "  X  ",
        " X X ",
        "X   X",
        "     ",
        "     ",
    ],
    "&": [
        " XX  ",
        "X  X ",
        " XX  ",
        "X  X ",
        " XX X",
    ],
    "*": [
        "X X X",
        " XXX ",
        "XXXXX",
        " XXX ",
        "X X X",
    ],
    "(": [
        "  X  ",
        " X   ",
        "X    ",
        " X   ",
        "  X  ",
    ],
    ")": [
        "  X  ",
        "   X ",
        "    X",
        "   X ",
        "  X  ",
    ],
    "-": [
        "     ",
        "     ",
        "XXXXX",
        "     ",
        "     ",
    ],
    "_": [
        "     ",
        "     ",
        "     ",
        "     ",
        "XXXXX",
    ],
    "+": [
        "     ",
        "  X  ",
        " XXXXX",
        "  X  ",
        "     ",
    ],
    "=": [
        "     ",
        "XXXXX",
        "     ",
        "XXXXX",
        "     ",
    ],
    "[": [
        "XXX  ",
        "X    ",
        "X    ",
        "X    ",
        "XXX  ",
    ],
    "]": [
        "  XXX",
        "    X",
        "    X",
        "    X",
        "  XXX",
    ],
    "{": [
        "  XX ",
        "  X  ",
        " X   ",
        "  X  ",
        "  XX ",
    ],
    "}": [
        " XX  ",
        "  X  ",
        "   X ",
        "  X  ",
        " XX  ",
    ],
    "|": [
        "  X  ",
        "  X  ",
        "  X  ",
        "  X  ",
        "  X  ",
    ],
    "\\": [
        "X    ",
        " X   ",
        "  X  ",
        "   X ",
        "    X",
    ],
    "/": [
        "    X",
        "   X ",
        "  X  ",
        " X   ",
        "X    ",
    ],
    ":": [
        "     ",
        "  X  ",
        "     ",
        "  X  ",
        "     ",
    ],
    ";": [
        "     ",
        "  X  ",
        "     ",
        "  X  ",
        " X   ",
    ],
    "'": [
        "  X  ",
        "  X  ",
        "     ",
        "     ",
        "     ",
    ],
    '"': [
        " X X ",
        " X X ",
        "     ",
        "     ",
        "     ",
    ],
    ",": [
        "     ",
        "     ",
        "     ",
        "  X  ",
        " X   ",
    ],
    ".": [
        "     ",
        "     ",
        "     ",
        "     ",
        "  X  ",
    ],
    "<": [
        "   X ",
        "  X  ",
        " X   ",
        "  X  ",
        "   X ",
    ],
    ">": [
        " X   ",
        "  X  ",
        "   X ",
        "  X  ",
        " X   ",
    ],
    "?": [
        " XXX ",
        "X   X",
        "   X ",
        "  X  ",
        "     ",
    ],
    " ": [
        "     ",
        "     ",
        "     ",
        "     ",
        "     ",
    ]
}

def string_to_grid(s: str):
    s = s.upper()
    grid = [[" " for _ in range(len(s) * 6 - 1)] for _ in range(5)]
    for idx, char in enumerate(s):
        char_grid = FONT.get(char, FONT[" "])
        for row in range(5):
            for col in range(5):
                grid[row][idx * 6 + col] = char_grid[row][col]
    return grid

def grid_to_commit_days(grid, start_date):
    # GitHub graph: 7 rows (Sun-Sat), 52 columns (weeks)
    # We'll center the 5-row grid vertically
    commit_days = []
    start = datetime.strptime(start_date, "%Y-%m-%d")
    for col in range(len(grid[0])):
        for row in range(5):
            if grid[row][col] == "X":
                # Map to GitHub graph: row+1 (to center), col
                day_offset = col * 7 + (row + 1)
                commit_date = start + timedelta(days=day_offset)
                commit_days.append(commit_date.date())
    return commit_days 